# Email Configurations
email:
    from: 'xxxxx@xxxx.com'
    pass: 'xxxxxxx'
    to: ['xxxxx@xxxx.com', 'yyyyy@xxxx.com']

# Activity Name
activityName: 'Volleyball'

# Recreational Centre ID
recreationalCentreId: 63

# Redis Configuration
redis:
    enabled: true
    expireMinutes: 1440
    url: redis://<USER>:<PASSWORD>@<SERVICE-IP>:<PORT>
