# Email Configurations
  email:
    from: "xxxxx@xxxx.com"
    pass: "xxxxxxx"
    to: "xxxxx@xxxx.com"

# Activity Configurations
  activity:
    name: "Volleyball Bonsor"
    daysAhead: 4

# Redis Configuration
  redis:
    enabled: true
    expireMinutes: 1440
    url: redis://<USER>:<PASSWORD>@<SERVICE-IP>:<PORT>